### ISSUE TITLE
Bug: No dual tap lands in Khans of Tarkir set

### ISSUE THREAD

**Issue by khansdrafter** [dr4fters/dr4ft#1087]
**Webpage**: dr4ft.info

No dual tap lands (swiftwater cliffs, blossoming sands, etc) in Khans of Tarkir set in draft or sealed.  tried multiple options; # of players, private\public, bots\no bots

Appears this problem just started happening in last 2-3 weeks

## Detailed Description

launch chrome
clear browsing data
go to dr4ft.info
update pack # to 4
change packs to Khans of Tarkir
create room
uncheck timer
start draft
click through draft to check for dual tap lands - none

**Comment by HerveH44** [comment]
Hi, thank you for opening the issue. It has already been solved in #1081 but has not been deployed on dr4ft.info yet.

@ZeldaZach Hey, could you update the main site to the last commit in order to not have this issue?

**Comment by ZeldaZach** [comment]
Yeah didn't realize. Site re-deployed!

**Comment by khansdrafter** [comment]
Looks like you are maybe still working this one, but still does not appear to be resolved

**Comment by tooomm** [comment]
Will open to double check once we are live again.
