### ISSUE TITLE
Selected card images disappear after a while in column view

### ISSUE THREAD

**Issue by demern** [dr4fters/dr4ft#206]
I've noticed recently that the enlarged card images that appear when hovering over a card in column view will flicker/disappear after a few seconds. They don't come back until you move the cursor off the card and back onto it. I'm not sure when this started happening, but it wasn't an issue a couple months ago at least in the same browser (Chrome). It makes it pretty annoying to try and read cards in column view.

Let me know if any more info would be helpful for trying to reproduce the issue. Thanks!

**Comment by HerveH44** [comment]
Hi, 

It should be solved in the last version. Could you try on dr4ft.info ?

Don't forget to refresh your cache (on chrome, it should be clicking on the refresh button while holding ctrl + shift).

**Comment by demern** [comment]
Ah, thank you. I was noticing the issue on dr4ft.com, but dr4ft.info looks like it's running a different version without this behavior.

Though now I'm noticing the latest set (GRN) isn't available on dr4ft.info like it is on dr4ft.com. But I guess that's a different problem (not even sure if the maintainers of this project also manage that site?) In any case, your comment resolves my initial issue. Thanks again!

**Comment by tooomm** [comment]
I had the same issue, thanks for reporting it @demern!

@dev-id dr4ft.com is still not on par with the repo and misses some fixes like this one.
